on:
    telegram_bot:
        event: text
        token: ${{secrets.TELEGRAM_YTDL}}
jobs:
    handle_message:
        name: Handle a telegram message
        runs-on: ubuntu-latest
        steps:
            - name: Setup youtube-dl
              run: |
                  apt update
                  apt install python3-pip
                  pip install youtube-dl
            - name: Download video
              run:
                youtube-dl
                    '${{on.telegram_bot.outputs.text}}' -o out 2> stderr.txt || true
            - name: Send video
              run:
                curl -v
                    -F chat_id=${{on.telegram_bot.outputs.chat.id}}
                    -F video=@out
                    -F reply_to_message_id=${{on.telegram_bot.outputs.message_id}}
                    https://api.telegram.org/bot${{secrets.TELEGRAM_YTDL}}/sendVideo 2>> stderr.txt || true
            - name: Send logs
              run:
                curl -v 
                    -F chat_id=${{on.telegram_bot.outputs.chat.id}}
                    -F document=@stderr.txt
                    -F reply_to_message_id=${{on.telegram_bot.outputs.message_id}}
                    https://api.telegram.org/bot${{secrets.TELEGRAM_YTDL}}/sendDocument
