on:
    telegram_bot:
        event: text
        token: ${{secrets.TELEGRAM_YTDL}}
jobs:
    handle_message:
        name: Handle a telegram message
        runs-on: ubuntu-latest
        steps:
            - name: Handle command
              env:
                TELEGRAM_TOKEN: ${{secrets.TELEGRAM_YTDL}}
              run:
                ./node_modules/youtube-dl/bin/youtube-dl
                    '${{on.telegram_bot.outputs.text}}' -o - |  curl -v
                    -F chat_id=${{on.telegram_bot.outputs.chat.id}}
                    -F video=-
                    -F reply_to_message_id=${{on.telegram_bot.outputs.message.id}}
                    https://api.telegram.org/bot${{secrets.TELEGRAM_YTDL}}/sendVideo
