on:
    telegram_bot:
        event: text
        token: ${{secrets.TELEGRAM_YTDL}}
jobs:
    handle_message:
        name: Handle a telegram message
        runs-on: ubuntu-latest
        steps:
            - name: Handle command
              run:
                ./node_modules/youtube-dl/bin/youtube-dl
                    '${{on.telegram_bot.outputs.text}}' -o out 2> stderr.txt 
                &&
                    curl -v
                    -F chat_id=${{on.telegram_bot.outputs.chat.id}}
                    -F video=@out
                    -F reply_to_message_id=${{on.telegram_bot.outputs.message.id}}
                    https://api.telegram.org/bot${{secrets.TELEGRAM_YTDL}}/sendVideo 2>> stderr.txt
                ||
                    curl -v 
                        -F chat_id=${{on.telegram_bot.outputs.chat.id}}
                        -F text=@stderr.txt
                        -F reply_to_message_id=${{on.telegram_bot.outputs.message.id}}
                        https://api.telegram.org/bot${{secrets.TELEGRAM_YTDL}}/sendMessage

